project:
  type: website

website:
  description: "My Experiments Log"
  site-url: https://experiments.narang99.in  # you must change this appropriately for RSS feeds to work properly
  title: "Hariom Narang's Experiments"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/narang99
format:
  html:
    mathjax: true
    respect-user-color-scheme: true
    theme:
      light: 
      - sandstone
      # - ft.scss
      # dark: cyborg
      # light: lux
      dark: cyborg
      # dark: darkly
      # - sandstone
      # - ft.scss
    # highlight-style: atom-one
    # highlight-style: haddock
    # highlight-style: gruvbox
    # code-block-border-left: true
