project:
  type: website

website:
  description: "My Experiments Log"
  site-url: https://experiments.narang99.in  # you must change this appropriately for RSS feeds to work properly
  title: "Hariom Narang's Experiments"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/narang99
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
