project:
  type: website

website:
  description: "My Experiments Log"
  site-url: https://experiments.narang99.in  # you must change this appropriately for RSS feeds to work properly
  title: "Hariom Narang's Experiments"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/narang99
format:
  html:
    highlight-style:
      dark: gruvbox-dark
      light: gruvbox
    # code-block-border-left: true
    mathjax: true
    theme:
      light: gruvbox-material-light.scss
      dark: gruvbox-material-dark.scss
    # sandstone
    # highlight-style: atom-one
    # highlight-style: haddock
    # highlight-style: gruvbox
    # code-block-border-left: true
